"""
Django settings for skillswap project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
from datetime import timedelta

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    # Django defaults
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'rest_framework.authtoken',  
    'rest_framework_simplejwt',
    'corsheaders',

    # for OAuth
    'django.contrib.sites',          # Required by allauth
    'allauth',                       # Core of django-allauth
    'allauth.account',               # Handles email & password auth
    'allauth.socialaccount',         # Base for social logins
    'allauth.socialaccount.providers.google',  # Google provider
    'allauth.socialaccount.providers.github',  # GitHub provider

    'dj_rest_auth',                  # REST endpoints for auth
    'dj_rest_auth.registration',     # Registration endpoints

    # local apps
    'accounts',
    'services',
    'userSkills',
    'skills',
    'listings',
    'reviews',
    'userblocks',
    'trade',
    'notification',
    'message',
]

# Allauth config
# Tell allauth there's no username field
# ACCOUNT_USER_MODEL_USERNAME_FIELD = None

# Link social accounts to existing users with matching email
ACCOUNT_ADAPTER = 'accounts.adapters.CustomAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'accounts.adapters.CustomSocialAccountAdapter'

# where to redirect after social login
# LOGIN_REDIRECT_URL = "http://localhost:5173/dashboard"
# SIGNUP_REDIRECT_URL = "http://localhost:5173/onboarding"
# LOGOUT_REDIRECT_URL = 'http://localhost:5173'



# Frontend URL (for redirects)
FRONTEND_URL = "http://localhost:5173"

# IMPORTANT: After OAuth success, redirect to our backend handler first
# This handler will generate tokens and then redirect to frontend
LOGIN_REDIRECT_URL = "/api/v1/auth/oauth/callback/"  # ✅ Backend URL, not frontend
SIGNUP_REDIRECT_URL = "/accounts/oauth/callback/"  # ✅ Same handler for both
LOGOUT_REDIRECT_URL = f"{FRONTEND_URL}/login"

# The rest of your allauth config stays the same
ACCOUNT_ADAPTER = 'accounts.adapters.CustomAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'accounts.adapters.CustomSocialAccountAdapter'

SOCIALACCOUNT_AUTO_SIGNUP = True
ACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = True  
ACCOUNT_AUTHENTICATION_METHOD = 'email'

# change to https in prod
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'http' 

SOCIALACCOUNT_AUTO_SIGNUP = True
ACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True

# help with username generation:
ACCOUNT_USERNAME_REQUIRED = True  
ACCOUNT_AUTHENTICATION_METHOD = 'email'  

# Logging configuration (optional but helpful)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'accounts': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# New login/signup configuration
# ACCOUNT_LOGIN_METHODS = {"email"}
# ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
# ACCOUNT_EMAIL_REQUIRED = True
# ACCOUNT_USERNAME_REQUIRED = False
# ACCOUNT_AUTHENTICATION_METHOD = 'email'  # use email to log in
# ACCOUNT_SIGNUP_FIELDS = {
#     "email": {"required": True},
#     "password1": {"required": True},
#     "password2": {"required": True},
# }

ACCOUNT_LOGIN_METHODS = ["email"]  # Only email login supported
ACCOUNT_SIGNUP_FIELDS = ["email", "password1", "password2"]


REST_USE_JWT = True


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware', 
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'skillswap.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'skillswap.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
SITE_ID = 1 # Needed for django-allauth

REST_USE_JWT = True  # Use SimpleJWT with dj-rest-auth

# SOCIALACCOUNT_PROVIDERS = {
#     "google": {
#         "APP": {
#             "client_id": os.getenv("GOOGLE_CLIENT_ID"),
#             "secret": os.getenv("GOOGLE_CLIENT_SECRET"),
#             "key": ""
#         },
#         "SCOPE": [
#             "openid",
#             "profile",
#             "email",
#         ],
#         "AUTH_PARAMS": {
#             "access_type": "online",
#         },
#     },
#     "github": {
#         "APP": {
#             "client_id": os.getenv("GITHUB_CLIENT_ID"),
#             "secret": os.getenv("GITHUB_CLIENT_SECRET"),
#             "key": ""
#         },
#         "SCOPE": [
#             "profile",
#             "email",
#         ],
#         "AUTH_PARAMS": {
#             "access_type": "online",
#         },
#     }
# }


# DRF JWT Authentication Setup
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
         "rest_framework_simplejwt.authentication.JWTAuthentication",
    )
}

# Allow frontend requests (temporarily allow all)
CORS_ALLOW_ALL_ORIGINS = True

AUTH_USER_MODEL = "accounts.User"


# Extend token lifetime (dev only)
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'USER_ID_FIELD': 'user_id',
    'USER_ID_CLAIM': 'user_id',
}
