import { useNavigate } from 'react-router-dom';
import { Mail, ChevronLeft } from 'lucide-react';
import Input from '../ui/Input';
import Button from '../ui/Button';
import { useState } from 'react';
import { useToast } from '@/hooks/useToast';
import { validateEmail } from '@/utils/ValidateEmail';
import { useEnterKey } from '@/hooks/useEnterKey';
import { useCrud, type EntityWithId } from '@/hooks/useCrud';
import emailjs from '@emailjs/browser';

interface ResetRequest extends EntityWithId {
  id: number;
  email?: string;
  reset_url?: string;
}

interface ForgotPasswordPayload {
  email: string;
}

const API_BASE_URL = import.meta.env.VITE_BASE_URL;

const ForgotPassword = () => {
  const navigate = useNavigate();
  const { showToast } = useToast();

  const { createItem, loading } = useCrud<ResetRequest>(
    `${API_BASE_URL}/auth/password/forgot/`,
  );

  const [email, setEmail] = useState('');

  const handleForgotPassword = async () => {
    if (!validateEmail(email)) {
      showToast('Please enter a valid email address', 'info');
      return;
    }

    const payload: ForgotPasswordPayload = { email };

    try {
      // Step 1: Call Django backend
      const response = await createItem(payload as any);

      // Step 2: Extract reset_url and email from backend
      const { reset_url, email: userEmail } = response as any;

      if (!reset_url || !userEmail) {
        throw new Error('Reset link not generated by backend');
      }

      // Step 3: Send email via EmailJS
      await emailjs.send(
        import.meta.env.VITE_EMAILJS_SERVICE_ID!,
        import.meta.env.VITE_EMAILJS_TEMPLATE_ID!,
        {
          to_email: userEmail,
          reset_link: reset_url,
        },
        import.meta.env.VITE_EMAILJS_PUBLIC_KEY!,
      );

      // Step 4: Feedback
      showToast('Password reset email sent! Check your inbox.', 'success');
      navigate('/login');
    } catch (err: any) {
      console.error(err);
      const errorMessage =
        err?.message || 'Failed to send reset link. Please try again.';
      showToast(errorMessage, 'error');
    }
  };

  useEnterKey(handleForgotPassword);

  return (
    <div className="mx-auto min-h-screen max-w-lg bg-white px-4 py-8">
      <div title="back">
        <ChevronLeft
          size={28}
          className="cursor-pointer"
          onClick={() => navigate(-1)}
        />
      </div>

      <div className="mt-14 flex flex-col text-center">
        <div>
          <h1 className="text-2xl font-bold md:text-3xl">
            Forgot your password?
          </h1>
          <p className="mt-2 text-gray-600">
            No worries! Enter your email address below and we'll send you a link
            to reset your password
          </p>
        </div>

        <div className="mt-10 mb-5 flex flex-col space-y-6">
          <Input
            icon={<Mail size={18} />}
            placeholderText="Your email address"
            type="email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
          />
        </div>

        <div className="text-center">
          <Button
            className="mb-4"
            onClick={handleForgotPassword}
            disabled={loading}
          >
            {loading ? 'Sending...' : 'Send Reset Link'}
          </Button>
          <p className="text-sm font-medium text-gray-600">
            Remember your password?{' '}
            <span
              onClick={() => navigate('/login')}
              className="cursor-pointer text-red-600 hover:underline hover:underline-offset-2"
            >
              Log in
            </span>
          </p>
        </div>
      </div>
    </div>
  );
};

export default ForgotPassword;
